# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Fri Oct 04 00:35:11 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(830, 453)
        MainWindow.setMinimumSize(QtCore.QSize(830, 453))
        MainWindow.setMaximumSize(QtCore.QSize(830, 453))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(5, 89, 757, 41))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.constants_update_edit = QtGui.QLineEdit(self.frame_2)
        self.constants_update_edit.setGeometry(QtCore.QRect(200, 10, 65, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constants_update_edit.sizePolicy().hasHeightForWidth())
        self.constants_update_edit.setSizePolicy(sizePolicy)
        self.constants_update_edit.setMinimumSize(QtCore.QSize(0, 17))
        self.constants_update_edit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.constants_update_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.constants_update_edit.setObjectName(_fromUtf8("constants_update_edit"))
        self.constants_update_button = QtGui.QPushButton(self.frame_2)
        self.constants_update_button.setGeometry(QtCore.QRect(275, 8, 80, 27))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.constants_update_button.sizePolicy().hasHeightForWidth())
        self.constants_update_button.setSizePolicy(sizePolicy)
        self.constants_update_button.setMinimumSize(QtCore.QSize(0, 27))
        self.constants_update_button.setObjectName(_fromUtf8("constants_update_button"))
        self.display_interval_button = QtGui.QPushButton(self.frame_2)
        self.display_interval_button.setGeometry(QtCore.QRect(695, 10, 55, 23))
        self.display_interval_button.setObjectName(_fromUtf8("display_interval_button"))

        self.selected_constant_mode_label = QtGui.QLabel(self.frame_2)
        self.selected_constant_mode_label.setGeometry(QtCore.QRect(365, 10, 100, 23))
        self.selected_constant_mode_label.setObjectName(_fromUtf8("selected_constant_mode_label"))
        
        self.display_interval_edit = QtGui.QLineEdit(self.frame_2)
        self.display_interval_edit.setGeometry(QtCore.QRect(625, 10, 35, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.display_interval_edit.sizePolicy().hasHeightForWidth())
        self.display_interval_edit.setSizePolicy(sizePolicy)
        self.display_interval_edit.setMinimumSize(QtCore.QSize(0, 17))
        self.display_interval_edit.setMaximumSize(QtCore.QSize(35, 16777215))
        self.display_interval_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.display_interval_edit.setObjectName(_fromUtf8("display_interval_edit"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(670, 10, 20, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(545, 10, 75, 22))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.constants_update_combobox = QtGui.QComboBox(self.frame_2)
        self.constants_update_combobox.setGeometry(QtCore.QRect(7, 10, 171, 22))
        self.constants_update_combobox.setObjectName(_fromUtf8("constants_update_combobox"))
        self.line_2 = QtGui.QFrame(self.frame_2)
        self.line_2.setGeometry(QtCore.QRect(540, 0, 3, 41))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.logger_log_memo = QtGui.QPlainTextEdit(self.centralwidget)
        self.logger_log_memo.setGeometry(QtCore.QRect(5, 173, 757, 275))
        self.logger_log_memo.setReadOnly(True)
        self.logger_log_memo.setObjectName(_fromUtf8("logger_log_memo"))
        self.readings_frame = QtGui.QFrame(self.centralwidget)
        self.readings_frame.setGeometry(QtCore.QRect(5, 131, 757, 41))
        self.readings_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.readings_frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.readings_frame.setObjectName(_fromUtf8("readings_frame"))
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(5, 5, 757, 41))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.stop_logging_button = QtGui.QPushButton(self.frame_3)
        self.stop_logging_button.setEnabled(False)
        self.stop_logging_button.setGeometry(QtCore.QRect(117, 10, 100, 23))
        self.stop_logging_button.setObjectName(_fromUtf8("stop_logging_button"))
        self.start_logging_button = QtGui.QPushButton(self.frame_3)
        self.start_logging_button.setGeometry(QtCore.QRect(7, 10, 100, 23))
        self.start_logging_button.setObjectName(_fromUtf8("start_logging_button"))
        self.load_on_button = QtGui.QPushButton(self.frame_3)
        self.load_on_button.setEnabled(False)
        self.load_on_button.setGeometry(QtCore.QRect(227, 10, 100, 23))
        self.load_on_button.setObjectName(_fromUtf8("load_on_button"))
        self.load_off_button = QtGui.QPushButton(self.frame_3)
        self.load_off_button.setEnabled(False)
        self.load_off_button.setGeometry(QtCore.QRect(337, 10, 100, 23))
        self.load_off_button.setObjectName(_fromUtf8("load_off_button"))
        self.label_7 = QtGui.QLabel(self.frame_3)
        self.label_7.setGeometry(QtCore.QRect(555, 10, 50, 22))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.com_port_edit = QtGui.QLineEdit(self.frame_3)
        self.com_port_edit.setGeometry(QtCore.QRect(610, 10, 50, 22))
        self.com_port_edit.setObjectName(_fromUtf8("com_port_edit"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(660, 10, 35, 22))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.baud_rate_edit = QtGui.QLineEdit(self.frame_3)
        self.baud_rate_edit.setGeometry(QtCore.QRect(700, 10, 50, 22))
        self.baud_rate_edit.setObjectName(_fromUtf8("baud_rate_edit"))
        self.com_connect_button = QtGui.QPushButton(self.frame_3)
        self.com_connect_button.setGeometry(QtCore.QRect(755, 10, 50, 22))   
        self.com_connect_button.setObjectName(_fromUtf8("com_connect_button"))        

        self.line_3 = QtGui.QFrame(self.frame_3)
        self.line_3.setGeometry(QtCore.QRect(540, 0, 3, 41))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(5, 47, 757, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_5dd_2 = QtGui.QLabel(self.frame)
        self.label_5dd_2.setGeometry(QtCore.QRect(10, 10, 34, 23))
        self.label_5dd_2.setObjectName(_fromUtf8("label_5dd_2"))
        self.browse_dirs_button = QtGui.QPushButton(self.frame)
        self.browse_dirs_button.setGeometry(QtCore.QRect(460, 10, 75, 23))
        self.browse_dirs_button.setObjectName(_fromUtf8("browse_dirs_button"))
        self.log_file_location_edit = QtGui.QLineEdit(self.frame)
        self.log_file_location_edit.setEnabled(True)
        self.log_file_location_edit.setGeometry(QtCore.QRect(50, 11, 401, 20))
        self.log_file_location_edit.setReadOnly(False)
        self.log_file_location_edit.setObjectName(_fromUtf8("log_file_location_edit"))
        self.line = QtGui.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(540, 0, 3, 41))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.log_interval_button = QtGui.QPushButton(self.frame)
        self.log_interval_button.setEnabled(True)
        self.log_interval_button.setGeometry(QtCore.QRect(695, 10, 55, 23))
        self.log_interval_button.setCheckable(False)
        self.log_interval_button.setObjectName(_fromUtf8("log_interval_button"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(670, 10, 20, 22))
        self.label.setObjectName(_fromUtf8("label"))
        self.log_interval_edit = QtGui.QLineEdit(self.frame)
        self.log_interval_edit.setGeometry(QtCore.QRect(625, 10, 35, 23))
        self.log_interval_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.log_interval_edit.setObjectName(_fromUtf8("log_interval_edit"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(545, 10, 75, 22))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "DC Logger", None))
        self.constants_update_edit.setText(_translate("MainWindow", "1", None))
        self.constants_update_button.setText(_translate("MainWindow", "Update", None))
        self.selected_constant_mode_label.setText(_translate("MainWindow", "Current mode: N/A", None))
        self.display_interval_button.setText(_translate("MainWindow", "Update", None))
        self.display_interval_edit.setText(_translate("MainWindow", "60", None))
        self.label_3.setText(_translate("MainWindow", "sec", None))
        self.label_2.setText(_translate("MainWindow", "Display interval", None))
        self.stop_logging_button.setText(_translate("MainWindow", "Stop logging", None))
        self.start_logging_button.setText(_translate("MainWindow", "Start logging", None))
        self.load_on_button.setText(_translate("MainWindow", "Turn Load On", None))
        self.load_off_button.setText(_translate("MainWindow", "Turn Load Off", None))
        self.label_7.setText(_translate("MainWindow", "COM port:", None))
        self.label_8.setText(_translate("MainWindow", "Baud:", None))
        self.label_5dd_2.setText(_translate("MainWindow", "Log to:", None))
        self.browse_dirs_button.setText(_translate("MainWindow", "Browse...", None))
        self.log_file_location_edit.setText(_translate("MainWindow", "C:\\", None))
        self.log_interval_button.setText(_translate("MainWindow", "Update", None))
        self.label.setText(_translate("MainWindow", "sec", None))
        self.log_interval_edit.setText(_translate("MainWindow", "1", None))
        self.label_4.setText(_translate("MainWindow", "Log interval", None))
        self.com_connect_button.setText(_translate("MainWindow", "Connect", None))

